local dialogtext = {
{"if","player","~=",4,"random"},
{"if","week","<",2,"random"},
{"if","w1vendor","==",4,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Flame on! Nice choice!","vs_w1p4vd_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","I may be a pyro, but I'm your pyro!","vs_w1p4vd_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Ya burned me!","vs_w1p4vd_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","I would have lit up the sky for you, but you picked someone else.","vs_w1p4vd_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","I've never met my match.","vs_w1p4vd_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","My kingdom for a fire extinguisher.","vs_w1p4vd_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
