local dialogtext = {
{"if","player","~=",4,"random"},
{"if","week","<",3,"random"},
{"goto","1"},

{"label","random"},
{"if","rnddialog","==",0,"3"},
{"if","rnddialog","==",1,"4"},
{"if","rnddialog","==",2,"5"},
{"if","rnddialog","==",3,"6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Beautiful. Beautiful. I just know you did great!","vs_w2p4e1_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","I can just tell, you took that information and ran with it!","vs_w2p4e1_rdm2.wav"},
	{"wait","end"},
{"label","3"},
    {"ns","If it's not hot dogs, it's mustard, if it's not mustard, it's relish.","vs_w2p4e1_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Every day I empty the water, every day the water gets dirty again.","vs_w2p4e1_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","You vant a hot dog?","vs_w2p4e1_rdm5.wav"},
    {"pg","Sure.","buyhotdog"},
	{"pg","No Thanks.","end"},
{"label","6"},
    {"ns","I got the dogs. You got cash?","vs_w2p4e1_rdm6.wav"},
	{"pg","Sure.","buyhotdog"},
	{"pg","No Thanks.","end"},
{"label","7"},
    {"ns","You want mustard or no mustard?","vs_w2p4e1_rdm7.wav"},
	{"pg","Sure.","buyhotdog"},
	{"pg","No Thanks.","end"},    
{"label","buyhotdog"},
    {"if","playercash",">=","hotdogprice","gethotdog"},
    {"n","My hot dogs cost $7.00. If you want one come back when you have enough money."},
    {"wait","end"},
{"label","gethotdog"},
    {"fun",inchotdog},
    {"goto","end"},
{"label","end"},
}
 return dialogtext
