local dialogtext = {
{"if","player","~=",1,"random"},
{"if","week","<",3,"random"},
{"if","w2vendor","==",2,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","You made the right connection; good choice!","vs_w2p1vb_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","We're connected! Good choice!","vs_w2p1vb_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","You made the wrong connection. Too bad.","vs_w2p1vb_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","We're not connected. Too bad.","vs_w2p1vb_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","It's all in how it sounds.","vs_w2p1vb_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","If it sounds good, it feels good.","vs_w2p1vb_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
