local dialogtext = {
{"if","player","~=",2,"random"},
{"if","week","<",4,"random"},
{"if","w3vendor","==",1,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Brilliant choice, I must say!","vs_w3p2va_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Well done! You've picked the best!","vs_w3p2va_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Rough going on that vendor choice.","vs_w3p2va_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Better luck next time with your vendor choices.","vs_w3p2va_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","A perfect day for cricket!","vs_w3p2va_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","It's almost time for tea!","vs_w3p2va_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
