local dialogtext = {
{"if","player","~=",4,"random"},
{"if","week","<",3,"random"},
{"if","w2vendor","==",2,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","You...are a genius, my friend!","vs_w2p4vb_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","When you picked me, you picked a winner!","vs_w2p4vb_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Hey. What can I say? You blew it!","vs_w2p4vb_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Hey, pick me next time and you'll have better sandwiches!","vs_w2p4vb_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","I gotta go over my bread order.","vs_w2p4vb_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","Ya use the best ingredients, you make the best sandwiches.","vs_w2p4vb_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
