local dialogtext = {
{"if","player","~=",4,"random"},
{"if","week","<",2,"random"},
{"if","w1vendor","==",1,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Just wait till you see our display, just wait!","vs_w1p4va_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Hey, you made the best choice ever!","vs_w1p4va_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Hey, look, you can't win them all.","vs_w1p4va_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Hey, better luck next time on your choice!","vs_w1p4va_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Whaddaya know? Another beautiful day!","vs_w1p4va_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","It's good, it's good, it's all good.","vs_w1p4va_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
