local dialogtext = {
{"if","player","~=",1,"random"},
{"if","week","<",4,"random"},
{"if","w3vendor","==",3,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Oi!  You rock!","vs_w3p1vc_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Oi! Me 'n me mates thank you for the gig!","vs_w3p1vc_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Oi!  So the place won't rock. No mind!","vs_w3p1vc_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Oi!  Hard luck on the vendor choices, mate!","vs_w3p1vc_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","God save the queen!","vs_w3p1vc_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","I'm leaving for Brixton this afternoon.","vs_w3p1vc_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
