local dialogtext = {
{"if","player","~=",2,"random"},
{"if","week","<",3,"random"},
{"if","w2vendor","==",4,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Hey, you really know how to pick 'em!","vs_w2p2vd_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","You picked me? You should be in sales!","vs_w2p2vd_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Better luck next time on your vendor choice.","vs_w2p2vd_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Next time spend some more time before you choose a different vendor.","vs_w2p2vd_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Here a tchocke, there a tchocke.","vs_w2p2vd_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","Everyone has a favorite tchocke.","vs_w2p2vd_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
