local dialogtext = {
{"if","player","~=",4,"random"},
{"if","week","<",3,"random"},
{"if","w2vendor","==",1,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Bueno! I'll make sure your food is delicious!","vs_w2p4va_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Hola! You made a good choice, I'll cook up a storm!","vs_w2p4va_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Pobrecito! You made a bad choice when you did not pick me!","vs_w2p4va_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Well, you will never taste my enchiladas.","vs_w2p4va_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","I need to call my family.","vs_w2p4va_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","It's important to have a big family.","vs_w2p4va_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
