local dialogtext = {
{"if","player","~=",1,"random"},
{"if","week","<",2,"random"},
{"if","w1vendor","==",2,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Aren't you a doll for choosing me! I can't wait!","vs_w1p1vb_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Thanks for choosing me, Sweetcakes!","vs_w1p1vb_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","No hard feelings, darlin!","vs_w1p1vb_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","I never hold a grudge, Sweetcakes.","vs_w1p1vb_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","I feel like goin' fishing!","vs_w1p1vb_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","It's a perfect day to write a country song!","vs_w1p1vb_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
