local dialogtext = {
{"if","player","~=",4,"random"},
{"if","week","<",3,"random"},
{"if","w2vendor","==",4,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},

{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","You made an excellent choice by going with Vitelli's.","vs_w2p4vd_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","You obviously have excellent taste in food.","vs_w2p4vd_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","You should have gone with New City's finest.","vs_w2p4vd_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","You may not like our chicken marsala, but your competition does.","vs_w2p4vd_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Come by and try the linguine.","vs_w2p4vd_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","I'm in the mood for nice carpaccio.","vs_w2p4vd_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
