local dialogtext = {
{"if","player","~=",3,"random"},
{"if","week","<",3,"random"},
{"goto","1"},

{"label","random"},
{"if","rnddialog","==",0,"3"},
{"if","rnddialog","==",2,"3"},
{"goto","4"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","You're ummm..well never mind. I hope I helped.","vs_w2p3e_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Well, I hope I didn't confuse you.","vs_w2p3e_rdm2.wav"},
	{"wait","end"},
{"label","3"},
    {"ns","Gotta find that darn defibrilator.","vs_w2p3e_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","I know it's here somewhere. Probably left it at work.","vs_w2p3e_rdm4.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
