local dialogtext = {
{"if","player","~=",3,"random"},
{"if","week","<",2,"random"},
{"if","w1vendor","==",2,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","You will have the most elegant accommodations!","vs_w1p3vb_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Sitting down will be the best part of your festival.","vs_w1p3vb_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Please! Don't talk to me!","vs_w1p3vb_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","I'm sure I don't know you, hmmmph!","vs_w1p3vb_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Vive la France.","vs_w1p3vb_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","Sacre bleu.","vs_w1p3vb_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
