local dialogtext = {
{"if","player","~=",1,"random"},
{"if","week","<",2,"random"},
{"if","w1vendor","==",1,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Thanks for choosing me to host your festival. I'm looking forward to it.","vs_w1p1va_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","You made the right choice by choosing me.","vs_w1p1va_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Your loss. You should have chosen me as your MC.","vs_w1p1va_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","I can't believe you didn't pick me.","vs_w1p1va_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","I feel a rave coming on.","vs_w1p1va_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","I need a new turntable.","vs_w1p1va_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
