local dialogtext = {
{"if","player","~=",4,"random"},
{"if","week","<",4,"random"},
{"if","w3vendor","==",1,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","You made the best choice possible. Nice Job!","vs_w3p4va_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","You clearly know your way around amusement rides!","vs_w3p4va_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","I wish you luck with the amusement rides at your event.","vs_w3p4va_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Maybe I'll see you at your event, but I won't be going on any rides.","vs_w3p4va_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Tighty righty, lefty loosey.","vs_w3p4va_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","If you screw things on too tight, you may strip the threads.","vs_w3p4va_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
