local dialogtext = {
{"if","player","~=",2,"random"},
{"if","week","<",2,"random"},
{"if","w1vendor","==",1,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Just wait till you taste the rigatoni!","vs_w1p2va_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","When you smell the marinara, you'll know you made the right choice with Buona Fortuna!","vs_w1p2va_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Well, I guess you'll never taste the fresh mozarella!","vs_w1p2va_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Oh, it's too bad you won't get to try our brick oven pizza!","vs_w1p2va_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Come stai?","vs_w1p2va_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","Buon giorno!","vs_w1p2va_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
