local dialogtext = {
{"if","player","~=",4,"random"},
{"if","week","<",4,"random"},
{"if","w3vendor","==",2,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","I'll put all my inventions to work for you.","vs_w3p4vb_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","My entire world of nuts and bolts at your disposal!","vs_w3p4vb_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Sorry I won't be able to use my inventions on your behalf.","vs_w3p4vb_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","What a shame we won't be working together.","vs_w3p4vb_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Innovation is the mother of invention.","vs_w3p4vb_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","An invention a day keeps the doctor away.","vs_w3p4vb_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
