local dialogtext = {
{"if","rnddialog","==",0,"1"},
{"if","rnddialog","==",1,"2"},
{"if","rnddialog","==",2,"3"},
{"if","rnddialog","==",3,"4"},
{"label","1"},
    {"ns","Custom tailoring is where it's at.","vs_mickey_rdm1.wav"},
	{"wait","end"},    
{"label","2"},
    {"ns","Custom pants for guys and gals!","vs_mickey_rdm3.wav"},
	{"wait","end"},    
{"label","3"},
    {"ns","Guard against risk with insurance!","vs_mickey_rdm4.wav"},
	{"wait","end"},    
{"label","4"},
    {"ns","Come see me for all your staffing needs.","vs_mickey_rdm5.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
