local dialogtext = {
{"if","player","~=",1,"random"},
{"if","week","<",3,"random"},
{"if","w2vendor","==",3,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","No doubt, you picked the best.","vs_w2p1vc_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"n","You went with the power when you picked the Verb!"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Yo, sorry you didn't pick me.","vs_w2p1vc_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","'Sup, yo? You must be straight trippin' for not pickin' me!","vs_w2p1vc_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Yo, my system be rockin' da hood!","vs_w2p1vc_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","Hip-Hop House brings on the sound in the blazin' clubs!","vs_w2p1vc_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
