local dialogtext = {
{"if","player","~=",2,"random"},
{"if","week","<",2,"random"},
{"if","w1vendor","==",2,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Outstandin' choice, pickin' me!","vs_w1p2vb_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","I must say you did a fine job pickin' me!","vs_w1p2vb_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Ya coulda had the best but ya went with the rest!","vs_w1p2vb_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","The best laid schemes of mice and men often go astray.","vs_w1p2vb_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Well done Cutty Sark!","vs_w1p2vb_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","Beauty's of a fadin' nature.  ","vs_w1p2vb_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
