local dialogtext = {
{"if","player","~=",4,"random"},
{"if","week","<",3,"random"},
{"if","w2vendor","==",3,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Just wait till you taste those fried corny dogs at your event!","vs_w2p4vc_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","You've got the King of Fried Food on your team now!","vs_w2p4vc_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Fried and denied. Oh well, better luck next time!","vs_w2p4vc_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","So you'll miss out on the best fried food in New City?  It's too late now.","vs_w2p4vc_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Hey, if it's not fried, it's not fried.","vs_w2p4vc_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","Jeesh, I'm fried today.","vs_w2p4vc_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
