local dialogtext = {
{"if","rnddialog","==",0,"1"},
{"if","rnddialog","==",1,"2"},
{"if","rnddialog","==",2,"3"},
{"if","rnddialog","==",3,"4"},
{"label","1"},
    {"ns","This sure beats the Medical Center.","vs_jgray_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","I hate bureaucracy.","vs_jgray_rdm2.wav"},
	{"wait","end"},
{"label","3"},
    {"ns","Time for a checkup.","vs_jgray_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Open wide and say, ahhhhhhh.","vs_jgray_rdm4.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
