local dialogtext = {
{"if","player","~=",2,"random"},
{"if","week","<",3,"random"},
{"if","w2vendor","==",1,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Nice choice, you won't regret it.","vs_w2p2va_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Smart choice, choosing me.","vs_w2p2va_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Yeah, well you didn't pick me.","vs_w2p2va_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Well, you coulda picked me...but you didn't.","vs_w2p2va_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","I'm feeling a little funky today.","vs_w2p2va_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","You look like you're in a funk.","vs_w2p2va_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
