local dialogtext = {
	{"if","evelynprogress","==",0,"A11"},
	{"if","evelynprogress","==",1,"A1ATD1"},
	{"if","evelynprogress","==",2,"A1ATD2"},
	{"if","evelynprogress","==",3,"A1ATD3"},
	{"if","evelynprogress","==",4,"A1ATD4"},
	{"if","evelynprogress","==",5,"A1ATD5"},
	{"if","evelynprogress","==",6,"A1ATD6"},
	{"if","evelynprogress","==",7,"A1ATD7"},
	{"if","evelynprogress","==",8,"A1ATD8"},
	{"if","evelynprogress","==",9,"A1ATD9"},
	{"if","evelynprogress","==",10,"A1ATD10"},
	{"if","evelynprogress","==",11,"A1ATD11"},
	{"if","evelynprogress",">=",12,"A1ATD12"},
	
	{"label","A11"},
		{"fun",incevelyn},
		{"fun",incstandon},
		{"fun",talkedtoevelyn},
		{"fun2",incvars,"journalprogress"},
		{"fun",getcheck},
		{"ns","Hey!  Welcome back to your team office! Here's your paycheck.  I hope you are looking forward to your next professional task here in downtown New City.  I have some new information this week, and as always, I'm here to help you anytime you need it.","VS_T2PXA1_01.ogg"},
		{"pg","Thanks Evelyn!  It's good to see you again.","A12"},
	{"label","A12"},
		{"ns","As you just learned from your CEO, there is still much work to be done on the oil spill in the New City River – and there are important tasks to be performed related to New City's recovery.  Remember, anytime you need help figuring out what to do next, come back to the office and talk to me – but the steps you will need to take to complete your task should be feeling familiar to you.","VS_T2PXA1_02.ogg"},
		{"pg","Thanks Evelyn.  So what is my first step?","A13"},
	{"label","A13"},
		{"ns","Will Standon is waiting for you at City Hall. Just as he did for you on your last task, he'll give you an assignment and guidelines for completing that task successfully.  Remember - Will is the client, so you need to always go through him when you have to make a decision on the job.  Now you'd better get going - he's waiting!","null.wav"},
		{"pg","Okay, Thanks!  I am going to see him now.","END"},
		{"pg","Thanks for the information. Before I go, I have some general game questions that maybe you can answer.","A14"},
	{"label","A1ATD1"},
		{"ns","You remember Will Standon, don't you?  He works for your client, the Mayor of New City.  You met with him last week.  Now, he is waiting for you at City Hall.  He is a busy man, and you shouldn't keep him waiting long! ","VS_T2PXA1_03.ogg"},
		{"pg","Thanks for the information. Before I go, I have some questions about the simulation.","A14"},
		{"pg","Thanks Evelyn.","END"},
	{"label","A1ATD2"},
		{"ns","Will Standon is still waiting for you at City Hall – and he is quite busy, so you shouldn't leave him waiting!  ","VS_T2PXA1_04.ogg"},
		{"pg","Okay, thanks Evelyn! I have another question you maybe able to answer.","A14"},
		{"pg","Thanks Evelyn. I don't have anymore questions at this time.","END"},
	{"label","A1ATD3"},
		{"ns","You have an appointment with D-Verb at the Hip House Loft.  You'd better get going!  ","VS_T2P1A1_01.ogg"},
		{"pg","I have some questions about the simulation.","A14"},
		{"pg","Great, Evelyn, Thank you.","END"},
	{"label","A1ATD4"},
		{"ns","You should go interview the spokespeople that D-Verb told you about.  If you've forgotten where your vendors are located, go see D-Verb again. He can remind you where they are.","VS_T2P1A1_02.ogg"},
		{"pg","I have some questions about the simulation.","A14"},
		{"pg","Thank you, Evelyn.","END"},
	{"label","A1ATD5"},
		{"ns","Have you found out everything you can about the spokespeople you were told to research?  If you're ready to make a recommendation, go see Will Standon and he will  give you your next step. If want to conduct interviews and need to know where the vendors are located, go see D-Verb.","VS_T2P1A1_03.ogg"},
		{"pg","I have some questions about the simulation.","A14"},
		{"pg","Okay, Evelyn, thanks.  I am on it.","END"},
	{"label","A1ATD6"},
		{"ns","Have you informed Will Standon about your choice for a spokesperson?  The next step for you is to finalize your choice with Mayor Gonzalez at City Hall.  ","VS_T2P1A1_04.ogg"},
		{"pg","I have some questions about the simulation.","A14"},
		{"pg","Thanks for the tip, Evelyn.","END"},
	{"label","A1ATD7"},
		{"ns","If you have received authorization from the Mayor to negotiate a deal with your vendor choice, the next step is to go back to that vendor and start negotiating.  Make sure you go to the meeting prepared with all the accurate information you could find.  I hope you wrote it all down somewhere!","VS_T2PXA1_05.ogg"},
		{"pg","I have some questions about the simulation.","A14"},
		{"pg","Okay, Evelyn! I'll be seeing you around…","END"},
	{"label","A1ATD8"},
		{"ns","You're well on your way! If you negotiated a deal with your vendor, go see Will Standon and get a contract drawn up!  He is waiting for you at City Hall.  ","VS_T2PXA1_06.ogg"},
		{"pg","I have some questions about the simulation.","A14"},
		{"pg","Thanks, Evelyn.","END"},
	{"label","A1ATD9"},
		{"ns","Did you get the spokesperson you picked to sign a contract to providetheir services?   If not, go back to where you first met the vendor and present them with the contract for signing.  ","VS_T2P1A1_05.ogg"},
		{"pg","I have some questions about the simulation.","A14"},
		{"pg","Okay, thanks!","END"},
	{"label","A1ATD10"},
		{"ns","You're moving right along. Did you hire a spokesperson?  If so, go get the contract counter-signed by Mayor Gonzalez!  She is waiting for you at City Hall.  ","VS_T2P1A1_06.ogg"},
		{"pg","I have some questions about the simulation.","A14"},
		{"pg","Okay, thanks!","END"},
	{"label","A1ATD11"},
		{"ns","Hey!  You're almost finished!  To complete your assigned task you will need to take your signed contract back to Will Standon.  He is waiting for you at City Hall.  ","VS_T2PXA1_07.ogg"},
		{"pg","I have some questions about the simulation.","A14"},
		{"pg","Thanks for your help Evelyn.  I'll see you soon.","END"},
	{"label","A1ATD12"},
		{"ns","Congratulations!  You've successfully hired your second vendor. Now, you may want to look around New City for people who can use your help.  You might find it rewarding!  ","VS_T2PXA1_08.ogg"},
		{"pg","I have some questions about the simulation.","A14"},
		{"pg","Okay, great.  I'll see you sometime soon, then, Evelyn.","END"},

--HELP SECTION
	
	{"label","A14"},
		{"ns","I'm here to help and I have a lot of information. Can I help you with something?  ","VS_T1PXA1_10.ogg"},
		{"pg","What is the object of this game?","A15A"},
		{"pg","How do I win the game?","A15B"},
		{"pg","Can I earn money in the game? ","A15C"},
		{"pg","How will I know how I am doing in the game?","A15D"},
		{"pg","Can I kill anyone in this game?","A15E"},
		{"pg","Do you have any general advice to help me out?","A15F"},
		{"pg","That's it for now, thanks!","END"},
	{"label","A15A"},
		{"ns","The object of this game is to guide New City through this current environmental disaster with successful planning and execution of your tasks. The team that gets the best results for the City wins!  Also, the sponsor of this game is going to make a donation to an en-vironmental advocacy organization on behalf of the winning team, so you can make a difference in the real world if you do a good job!","VS_T1toT2PXA1_11.ogg"},
		{"pg","Got it, thanks. I have another question you maybe able to answer.","A14"},
		{"pg","Thanks Evelyn. I don't have anymore questions at this time.","END"},
	{"label","A15B"},
		{"ns","For every task, each member of your team will be asked to hire one vendor from a list of four candidates. Find out as much as you can about each vendor and pick the one who best conforms to the guidelines that Will Standon gives you. The team who identifies the best vendors throughout the four tasks, wins! Your team is then ranked with others in your class, school, state and around the nation.","VS_T1toT2PXA1_12.ogg"},
		{"pg","Okay, thanks.  I'll keep that in mind. I have another question you maybe able to answer.","A14"},
		{"pg","Thanks Evelyn. I don't have anymore questions at this time.","END"},
	{"label","A15C"},
		{"ns","You can earn money in different ways. You can earn bonuses for finding people around New City who need information or help.  You can also sell and redeem the trash and recyclables you collect around town.  There are other ways to earn money, too.  Explore the world to find them. ","VS_T1toT2PXA1_13.ogg"},
		{"pg","Okay, great! I have another question you maybe able to answer.","A14"},
		{"pg","Thanks Evelyn. I don't have anymore questions at this time.","END"},
	{"label","A15D"},
		{"ns","During the game, people you meet will tell you how you are doing with your missions. You can see the personal money you've earned by checking your inventory.  At the end of the game, your teammates and you will find out how well you did overall and how your team ranked against competing teams around the country.","VS_T1toT2PXA1_14.ogg"},
		{"pg","Okay thanks, Evelyn. I have another question you maybe able to answer.","A14"},
		{"pg","Thanks Evelyn. I don't have anymore questions at this time.","END"},
	{"label","A15E"},
		{"ns","Just like in real life, violence is not a good way to get things done in New City.  Instead, we use our brains to solve problems and get ahead","VS_T1toT2PXA1_15.ogg"},
		{"pg","Right on, Evelyn. I have another question you maybe able to answer.","A14"},
		{"pg","Thanks Evelyn. I don't have anymore questions at this time.","END"},
	{"label","A15F"},
		{"ns","Yes, I do. Pay attention to the guidelines you get from Will Standon, and find as much accurate information as you can before you make decisions. Personally, I suggest writing important information down in your Journal so you can use it when the time comes. Also stay on top of the news and talk to people around town. You never know what you might learn.","VS_T1toT2PXA1_16.ogg"},
		{"pg","Okay, thanks Evelyn! I have another question you maybe able to answer.","A14"},
		{"pg","Thanks Evelyn. I don't have anymore questions at this time.","END"},

--END

	{"label","END"},
		{"fun3",storescore,scoreconvo,scorestr},
}
return dialogtext
