local dialogtext = {
{"if","player","~=",1,"random"},
{"if","week","<",4,"random"},
{"if","w3vendor","==",2,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Thanks, man we're going to play all night, man.","vs_w3p1vb_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Picking us was a farout idea, thanks!","vs_w3p1vb_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","It's cool, man. Someone else picked me for another show.","vs_w3p1vb_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","You didn't pick us as your vendor but I'm going with the flow, man.","vs_w3p1vb_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","A perfect day for a hacky sack!","vs_w3p1vb_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","Far out, man!","vs_w3p1vb_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
