local dialogtext = {
{"if","player","~=",4,"random"},
{"if","week","<",4,"random"},
{"if","w3vendor","==",3,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","I can't wait till we get going!","vs_w3p4vc_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","I can't wait for your festival!","vs_w3p4vc_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Oh well, maybe next time.","vs_w3p4vc_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","I can't wait to see how your fesitval turns out, without my rides.","vs_w3p4vc_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Fun is the ultimate thing.","vs_w3p4vc_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","If it isn't fun, it ain't from Eddie.","vs_w3p4vc_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
