local dialogtext = {
{"if","player","~=",3,"random"},
{"if","week","<",4,"random"},
{"if","w3vendor","==",2,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","I appears that you and I will be working together.","vs_w3p3vb_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Choosing me could mean that your event will make the most money.","vs_w3p3vb_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","The implications of not choosing me will become clear later.","vs_w3p3vb_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Choosing someone else to handle your security could mean that your event loses money.","vs_w3p3vb_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Security, is a warm assumption.","vs_w3p3vb_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","One thing is for sure, it's good to be secure.","vs_w3p3vb_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
