local dialogtext = {
{"if","player","~=",2,"random"},
{"if","week","<",3,"random"},
{"if","w2vendor","==",3,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","We will make the very finest works to honor your excellent decision.","vs_w2p2vc_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","I am honored to be your vendor of choice.","vs_w2p2vc_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","I will, of course, honor your choice.","vs_w2p2vc_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Custom Designs regrets the loss of your business.","vs_w2p2vc_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Success is 99% failure.","vs_w2p2vc_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","When love is deep, much can be accomplished.","vs_w2p2vc_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
