local dialogtext = {
{"if","player","~=",3,"random"},
{"if","week","<",2,"random"},
{"if","w1vendor","==",3,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","We will deploy in strict accordance with your instructions, thanks for the order!","vs_w1p3vc_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Rest assured that our deployment will meet your specifications.","vs_w1p3vc_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Standing down based on your negative assessment of our capabilities.","vs_w1p3vc_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Deployment cancelled due to lack of interest by you,","vs_w1p3vc_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Shhhh! Did you hear that?","vs_w1p3vc_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","Planning is the key to logistical deployment.","vs_w1p3vc_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
