local dialogtext = {
{"if","player","~=",4,"random"},
{"if","week","<",2,"random"},
{"if","w1vendor","==",2,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","The boys and I will do a great job for you!","vs_w1p4vb_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","The whole gang is excited about working for you!","vs_w1p4vb_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","I guess I'll go to the Fireman's ball since I won't be working for you.","vs_w1p4vb_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Do you have bad luck at poker, too?","vs_w1p4vb_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","A good day for shining the firehouse pole.","vs_w1p4vb_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","I need a new pack of cards.","vs_w1p4vb_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
