local dialogtext = {
{"if","player","~=",1,"random"},
{"if","week","<",4,"random"},
{"if","w3vendor","==",4,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","You obviously have very good taste in music.","vs_w3p1vd_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","I think you know how smart you were to pick me.","vs_w3p1vd_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Like, I knew you wouldn't pick me.","vs_w3p1vd_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","You clearly have no taste in music, or you would have picked me.","vs_w3p1vd_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","It's always so hot around here.","vs_w3p1vd_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","I'm always chilly around here.","vs_w3p1vd_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
