local dialogtext = {
{"if","player","~=",3,"random"},
{"if","week","<",2,"random"},
{"if","w1vendor","==",1,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","You'll be glad you went with the leader in portable sanitation!","vs_w1p3va_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Wait till you see our new pumping truck!","vs_w1p3va_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","I can't imagine why you didn't pick me.","vs_w1p3va_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","You'll never get to see our new pumping truck!","vs_w1p3va_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","This place could use some porta potties.","vs_w1p3va_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","I'm feeling energized today.","vs_w1p3va_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
