local dialogtext = {
{"if","player","~=",3,"random"},
{"if","week","<",4,"random"},
{"if","w3vendor","==",3,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Heeya! We will conquer our fears together!","vs_w3p3vc_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Heeya! Our alignment will be complete.","vs_w3p3vc_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","It is unfortunate that our paths are not aligned.","vs_w3p3vc_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","How regrettable that our energy will not comingle.","vs_w3p3vc_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Heeya!","vs_w3p3vc_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","The universe is forever expanding","vs_w3p3vc_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
