local dialogtext = {
{"if","player","~=",4,"random"},
{"if","week","<",2,"random"},
{"if","w1vendor","==",3,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Good choice. I can promise you an excellent return on your investment.","vs_w1p4vc_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Your successful evaluation of our assets and liabilities is to be commended.","vs_w1p4vc_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","You're return on investment would have been much higher if you had picked me.","vs_w1p4vc_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Your unsuccessful assessment of our assets and liabilities is to be lamented.","vs_w1p4vc_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Maybe I should start a hedge fund.","vs_w1p4vc_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","Third quarter profits are up 23% before expenses.","vs_w1p4vc_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
