local dialogtext = {
{"if","rnddialog","==",0,"1"},
{"if","rnddialog","==",1,"2"},
{"if","rnddialog","==",2,"3"},
{"if","rnddialog","==",3,"4"},
{"label","1"},
    {"ns","Yep. Fill it and bill it!","vs_billgas_rdm1.wav"},
	{"pg","okay.","end"},
	--{"wait","end"},
{"label","2"},
    {"ns","Gotta get around to inspecting the fleet.","vs_billgas_rdm2.wav"},
	{"pg","okay.","end"},
	--{"wait","end"},
{"label","3"},
    {"ns","I never saw a tank I couldn't pump.","vs_billgas_rdm3.wav"},
	{"pg","okay.","end"},
	--{"wait","end"},
{"label","4"},
    {"ns","A little air freshener always helps.","vs_billgas_rdm4.wav"},
	{"pg","okay.","end"},
	--{"wait","end"},
{"label","end"},
}
 return dialogtext
