local dialogtext = {
{"if","player","~=",3,"random"},
{"if","week","<",3,"random"},
{"if","w2vendor","==",3,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","You picking me was the best news I've received since I left Rosendale.","vs_w2p3vc_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","I thought leaving Rosendale Medical Center was good but being picked by you was better!","vs_w2p3vc_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Thanks to you I'm heading back to my old job.","vs_w2p3vc_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Just when our company was starting to get somewhere, you picked someone else.","vs_w2p3vc_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","I need a break.","vs_w2p3vc_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","Above all do no harm.","vs_w2p3vc_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
