local dialogtext = {
{"if","rnddialog","==",0,"1"},
{"if","rnddialog","==",1,"2"},
{"if","rnddialog","==",2,"3"},
{"if","rnddialog","==",3,"4"},
{"label","1"},
    {"ns","Was it a boom, or a bubble?","vs_markh_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","I've got to restart the server.","vs_markh_rdm2.wav"},
	{"wait","end"},
{"label","3"},
    {"ns","Whatever you do, don't double click.","vs_markh_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Downloading without paying only hurts the artist.","vs_markh_rdm4.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
