local dialogtext = {
{"if","player","~=",2,"random"},
{"if","week","<",4,"random"},
{"if","w3vendor","==",3,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","You did your job well. Congratulations.","vs_w3p2vc_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Your choice is to be congratulated.","vs_w3p2vc_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","You made your choice. Now live with it.","vs_w3p2vc_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","I can't help you if you don't hire me.","vs_w3p2vc_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Who invented the Internet?","vs_w3p2vc_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","Happiness is a warm server.","vs_w3p2vc_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
