local dialogtext = {
{"if","player","~=",3,"random"},
{"if","week","<",3,"random"},
{"if","w2vendor","==",2,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","I thank you, and my defibrilator thanks you.","vs_w2p3vb_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","I'm pretty sure you chose me.","vs_w2p3vb_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","I'm pretty sure you didn't choose me.","vs_w2p3vb_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","I seem to remember that you chose someone else.","vs_w2p3vb_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Gotta find that darn defibrilator.","vs_w2p3vb_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","I know it's here somewhere. Probably left it at work.","vs_w2p3vb_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
