local dialogtext = {
{"if","player","~=",2,"random"},
{"if","week","<",2,"random"},
{"if","w1vendor","==",3,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","When you see where I'm going to take your people you'll wish you were coming!","vs_w1p2vc_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","You picked the first name in shopping!","vs_w1p2vc_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Wow, I could have really made them shop till they dropped!","vs_w1p2vc_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Oh, the shopping you're going to miss!","vs_w1p2vc_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","There's a sale on today.","vs_w1p2vc_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","They were on sale so I bought three pair.","vs_w1p2vc_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
