local dialogtext = {
{"if","player","~=",3,"random"},
{"if","week","<",3,"random"},
{"if","w2vendor","==",1,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","We're ready to serve. Good choice!","vs_w2p3va_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Can't wait to put all those certifications to work for you!","vs_w2p3va_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Good luck with whoever you chose!","vs_w2p3va_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","All those certifications, and you picked someone else.","vs_w2p3va_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Gotta get that N.P.T.S.C. application in today.","vs_w2p3va_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","There's nothing more comforting than being fully certified.","vs_w2p3va_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
