local dialogtext = {
{"if","player","~=",3,"random"},
{"if","week","<",3,"random"},
{"if","w2vendor","==",4,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",1,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",1,"2"},
    {"ns","Thanks for picking me, I've already started training!","vs_w2p3vd_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Now that you've picked me maybe I can get some new clothes.","vs_w2p3vd_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",1,"4"},
    {"ns","Your bad choice will be our little secret. OK?","vs_w2p3vd_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","I really wasn't prepared for you to pick someone else.","vs_w2p3vd_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Today's a good day to do some training!","vs_w2p3vd_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","I'm in the mood for a Civil War re-enactment.","vs_w2p3vd_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
