local dialogtext = {
{"if","player","~=",1,"random"},
{"if","week","<",4,"random"},
{"if","w3vendor","==",1,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","You'll be thrillin' like a villian when I start chillin'.","vs_w3p1va_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Straight outta New City with the def mix for you.","vs_w3p1va_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","That's some whack vendor decision you made, man.","vs_w3p1va_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","On the vendor decision?  You missed it, I dissed it.","vs_w3p1va_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Number one in the hood, G.","vs_w3p1va_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","I keeps it real.","vs_w3p1va_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
