local dialogtext = {
	{"fun3",setvar,"scoreconvo","nlc_math"},
    {"if","mathtest","==",0,"1a"},
    {"if","mathtest",">",0,"atd"},
{"label","atd"},
    {"ns","Well, I am so sad you are leaving town... I think we could have been great friends, I mean, because you, like, enjoy helping me with math. You know, we'll all miss you! Thanks for your help! I'll never forget it!","vs_nl_w4pxmath07.wav"},
    {"pg","Maybe we'll meet again some day.","end"},

{"label","1a"},
    {"ns","Like, hi! I hope you are here to see if I need help with my math homework, because, like, my homework is really hard this week. I only have a little bit left to do, though. Would you like to help me finish it? Please?","vs_nl_w4pxmath01.wav"},
    {"pg","Sure, I could spare a minute. Let's see what you have left to solve.","2a"},
    {"pg","Math problems? Again? No offense, but I should run. It's been great knowing you, though. Bye.","end"},

{"label","2a"},
    {"ns","So, the first problem here states, \"If x^2=1 and |x|=1, then which of the following must be true?\"","vs_nl_w4pxmath02.wav"},
    {"pg","x= +1.","3a"},
    {"ps","x= + or - 1.","a"},
    {"pg","x< 0.","3a"},
    {"pg","x= -1.","3a"},
    {"fun",incresult},
    {"fun2",incplayercash,5},
{"label","3a"},
    {"ns","Okay. Next, it says, \"Plot each possible value of x and y for the expression Y=3x\". What is the slope of the line that connects each value of x and y?","vs_nl_w4pxmath03.wav"},
    {"pg","x= + or - 2.","4a"},
    {"pg","x=-2.","4a"},
    {"ps","3.","b"},
    {"pg","= Square root of 2.","4a"},
    {"fun",incresult},
    {"fun2",incplayercash,5},
{"label","4a"},
    {"ns","Okay, now this last one gave me a little trouble. It says, \"if (x+3)/2 >= 3/2, then which of the following must be true?\"","vs_nl_w4pxmath04.wav"},
    {"pg","|x| = -x.","5a"},
    {"pg","-6<x<=0.","5a"},
    {"pg","|x| = -3.","5a"},
    {"ps","x>=6.","c"},
    {"fun",incresult},
    {"fun2",incplayercash,5},
{"label","5a"},
    {"ns","I have the rest of these problems solved, so that's the last of my homework this week! Oh, awesome! Now let me check the answer key and see how you did...","vs_nl_w4pxmath05.wav"},
    {"pg","I'm glad I could help. Please let me know how I did whenever you are ready.","math2results"},
{"label","math2results"},
    {"if","mathresult","<",2,"6a"},
    {"if","mathresult","<",3,"6b"},
    {"if","mathresult","==",3,"6c"},
{"label","6a"},
    {"ns","Oh, gee. That was pretty bad... Are you sure you are good at math? You certainly weren't able to help me very much with my math homework.","vs_nl_wxpxmath01.wav"},
    {"pg","I'm sorry I couldn't be more helpful.","7a"},

{"label","7a"},
    {"fun",incmath},
    {"fun",incsq},
    {"ns","So, like, thanks for your time. That was like, really awesome. Hey, I hear it's your last week here in New City. You know, I really hope you can come back here some day soon. We'll all miss you!","vs_nl_w4pxmath06.wav"},
    {"pg","Well, maybe we will pass by each other sometime before I leave. Talk to you soon!","end"},

{"label","6b"},
    {"ns","Hey, you didn't do such a bad job. You could have done better, but all in all, you were able to help me with my math homework this week.","vs_nl_wxpxmath02.wav"},
    {"pg","I'm sure you'll do just fine all by yourself - but I hope that I've been helpful.","7a"},

{"label","6c"},
    {"ns","Great! That was terrific! You clearly know a lot about math - and you helped me a lot with my homework this week. My teacher is going to be proud of me!","vs_nl_wxpxmath03.wav"},
    {"pg","I am happy to have helped!","7a"},

{"label","end"},
	{"fun3",storenlcscore,scoreconvo,scorestr},
}
 return dialogtext
