local dialogtext = {
{"if","player","~=",2,"random"},
{"if","week","<",4,"random"},
{"if","w3vendor","==",2,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","I'm so glad you chose us!","vs_w3p2vb_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Vizible will do a great job for you!","vs_w3p2vb_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","I hope your event works ok without us.","vs_w3p2vb_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Good luck with whoever you choose instead of us.","vs_w3p2vb_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","I've got to get those ads out.","vs_w3p2vb_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","A day without a deadline is like a day without sunshine.","vs_w3p2vb_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
