local dialogtext = {
{"if","player","~=",3,"random"},
{"if","week","<",4,"random"},
{"if","w3vendor","==",1,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","I will definitely be prepared for your event!","vs_w3p3va_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","I wish I could tell my mother that you selected us!","vs_w3p3va_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Thankfully, my mother will never know you picked someone else.","vs_w3p3va_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","What a shame you picked someone else for your event.","vs_w3p3va_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Volunteerism is a good thing.","vs_w3p3va_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","Small is good.","vs_w3p3va_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
