local dialogtext = {
{"if","player","~=",1,"random"},
{"if","week","<",2,"random"},
{"if","w1vendor","==",4,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Hey, don't look at me, it was your decision.","vs_w1p1vd_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","You've got a clown on your payroll!","vs_w1p1vd_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","You coulda' had the King of Clowns!","vs_w1p1vd_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Sorry, kid, you blew it!","vs_w1p1vd_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","A clown's work is never done.","vs_w1p1vd_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","Hey, kid, I'm just clowning around.","vs_w1p1vd_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
