local dialogtext = {
{"if","rnddialog","==",0,"1"},
{"if","rnddialog","==",1,"2"},
{"if","rnddialog","==",2,"3"},
{"if","rnddialog","==",3,"4"},
{"label","1"},
    {"ns","When you're talkin' to me, you're talkin' to the source!","vs_franco_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","I got a nose for information!","vs_franco_rdm2.wav"},
	{"wait","end"},
{"label","3"},
    {"ns","A clue a day means I get paid!","vs_franco_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Remember to call your mother every day!","vs_franco_rdm4.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
