local dialogtext = {
{"if","player","~=",2,"random"},
{"if","week","<",4,"random"},
{"if","w3vendor","==",4,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","You've got Jimmy Boy on your team!","vs_w3p2vd_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","When you choose ol' Jimmy you choose the best!","vs_w3p2vd_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Ya coulda had ol' Jiiiimmy Boy!","vs_w3p2vd_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Hey, all you had to do was hire me!","vs_w3p2vd_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Just gimme some glue and a brush.","vs_w3p2vd_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","I never saw a poster I didn't like.","vs_w3p2vd_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
