local dialogtext = {
{"if","player","~=",1,"random"},
{"if","week","<",2,"random"},
{"if","w1vendor","==",3,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Daaag. You know what's happening and you picked me!  ","vs_w1p1vc_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Excellent choice, my man!","vs_w1p1vc_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Daaag. You musta bumped your head before you made your decision!","vs_w1p1vc_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Hey Dawg! You missed your big chance!","vs_w1p1vc_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Hey, Dawg you're lookin' good!","vs_w1p1vc_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","Hey, Dawg it's another chill day in the city!","vs_w1p1vc_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
