local dialogtext = {
	{"fun3",setvar,"scoreconvo","nlc_tg"},
{"if","tourguide","==",0,"asd"},
{"if","tourguide","==",1,"1"},
{"if","tourguide","==",2,"atd1"},
{"if","tourguide","==",3,"atd2"},

{"label","asd"},
    {"ns","Hello again! Welcome back to town!  I hear you are leaving soon  so as the official representative of the New Tourism bureau, I'd like to wish you the best of luck. Also, if there is anything I can help you with before you leave – just let me know.","VS_T3PXFUNCH_09.ogg"},
    {"pg","Thanks for the offer. I was just trying to pass through, though See you around!","end"},
    {"pg","Thanks. I am looking for a way to make some personal money here in town.  Do you have any ideas?","atd1"},
    --{"pg","Great - I was actually looking for information.  Can you help?","assistance"},

{"label","1"},
    {"ns","Hello again! I am happy to see you around town again. Remember, as the local tour guide, I know a bit about the area - and I can help you if you need help getting around. If you already know your way around town, though, I have a challenge for you: I'll give you a cash bonus if you can correctly answer some trivia questions.","VS_T3PXFUNCH_01.ogg"},
    {"pg","I am ready for one of your local trivia challenges! Let's begin.","2"},
    {"pg","I'm not sure I've paid enough attention to details around town this week so I don't think I'm ready yet.","end"},
    --{"pg","Actually, I need help finding someone around town, can  you help me?","assistance"},

{"label","2"},
	{"fun",tourguideto3},
    {"ns","Okay, I hope you're ready  because these are my hardest questions yet.  Let's begin by telling me: Which of the following periodicals are available for sale each week at the Newsstand in front of City Hall?","VS_T3PXFUNCH_02.ogg"},
    {"pg","New City Examiner","3"},
    {"pg","Elliot County Enquirer","3"},
    {"pgs","Both the New City Examiner and the Elliot County Enquirer.","2score","a"},
    {"pg","Neither are the names of periodicals available for sale each week at the Newsstand.","3"},
{"label","2score"},
    {"fun",addtouristscore},
    {"goto","3"},
{"label","3"},
    {"ns","What is the name of the character that sells hot dogs near City Hall?","VS_T3PXFUNCH_03.ogg"},
    {"pg","Joey Cramarossa","4"},
    {"pg","Alberto Vitelli","4"},
    {"pg","Mickey Jones","4"},
    {"pgs","Sloboloasch","3score","b"},
{"label","3score"},
    {"fun",addtouristscore},
    {"goto","4"},
{"label","4"},
    {"ns","Okay, so here's another question to see how closely you've been paying attention to details: how many flags are there flying in front of City Hall?","VS_T3PXFUNCH_04.ogg"},
    {"pgs","None","4score","c"},
    {"pg","One","5"},
    {"pg","Two","5"},
    {"pg","Three","5"},
{"label","4score"},
    {"fun",addtouristscore},
    {"goto","5"},   
{"label","5"},
    {"ns","What color are the drapes in the Mayor's office?","VS_T3PXFUNCH_05.ogg"},
    {"pg","Blue","6"},
    {"pgs","Pink","5score","d"},
    {"pg","White","6"},
    {"pg","Black","6"},
{"label","5score"},
    {"fun",addtouristscore},
    {"goto","6"},   
{"label","6"},
    {"ns","So here is one last question to test your attention to detail: What color is Will Standon's tie? ","VS_T3PXFUNCH_06.ogg"},
    {"pg","Pink","7"},
    {"pg","Red","7"},
    {"pg","Green","7"},
    {"pgs","Blue","6score","e"},
{"label","6score"},
    {"fun",addtouristscore},
    {"goto","7"},

{"label","7"},
{"fun",incsq},
    {"fun",calctourcash},
    {"ns2","Well that's all the questions I have for you, for now. This time, out of my 5 questions, you answered %d correctly. You earned $%d for your answers.  Don't spend it all in one place! ","VS_T3PXFUNCH_07.ogg","touristscore","tourcash"},
    {"pg","Thanks. ","8"},

{"label","8"},
    {"ns","Well there you have it,  paying attention to details around New City – and in life – is always good for your pocketbook! Well, that's it for all of my challenges! I hope you have found them rewarding.","VS_T3PXFUNCH_08.ogg"},
    {"pg","Okay, great.  See you later!","end"},

{"label","atd1"},
    {"ns","You still have a few opportunities to make some cash, if you like.  There are quite a few people around town who may need help, and who can reward you.  When you move along a little further in your investigation, maybe I'll even have a few last questions for you.","VS_T3PXFUNCH_10.ogg"},
    {"pg","Alright, I'll come back when I have gotten a little further in my assignment. I'll look around in the meantime.","end"},

{"label","atd2"},
    {"ns","I don't have any more trivia challenges for you – but, as the official representative of the New City Tourism Bureau, I would like to thank you for your visit.  I hope to see you in town again soon!","VS_T3PXFUNCH_11.ogg"},
    {"pg","The pleasure has been mine.  Thanks for everything!","end"},
    --{"pg","","assistance"},
	

{"label","end"},
	{"fun3",storenlcscore,scoreconvo,scorestr},
}
 return dialogtext
