local dialogtext = {
{"if","player","~=",4,"random"},
{"if","week","<",4,"random"},
{"if","w3vendor","==",4,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","I made the sale, you made a good choice!","vs_w3p4vd_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","We're going to do great things together.","vs_w3p4vd_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","I guess I need to work on my sales skills.","vs_w3p4vd_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","Ok, so we won't change the world together.","vs_w3p4vd_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Flip the switch and watch the thing fly!","vs_w3p4vd_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","Rides light up the night with excitement!","vs_w3p4vd_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
