local dialogtext = {
	{"fun3",setvar,"scoreconvo","nlc_tg"},
{"if","tourguide","==",0,"asd"},
{"if","tourguide","==",1,"1"},
{"if","tourguide","==",2,"atd1"},
{"if","tourguide","==",3,"atd2"},

{"label","asd"},
    {"ns","Well, hello there! On behalf of the New City tourism board, I'd like to wish you a warm welcome to New City.  I am the local tour guide, I know a bit about the area - and I can help you if you need help getting around!","VS_T1PXFUNCH_09.ogg"},
    {"pg","No, thanks. I was just trying to pass through.","end"},
    {"pg","I am looking for a way to make some personal money here in town.  Do you have any ideas?","atd1"},
    --{"pg","Okay, then - I am looking for help getting around.  Do you have a moment?","assistance"},

{"label","1"},
    {"ns","On behalf of the New City tourism board, I'd like to wish you a warm welcome to New City. I am the local tour guide, I know a bit about the area - and I can help you if you need help getting around. If you already know your way around town, though, I have a challenge for you: I'll give you a cash bonus if you can correctly answer some trivia questions.","VS_T1PXFUNCH_01.ogg"},
    {"pg","Sure - I am ready for a local trivia challenge! Bring it on.","2"},
    {"pg","I haven't really been in town for that long – so I don't think I'm ready to test my local knowledge quite yet. ","end"},
    --{"pg","Actually, I'd like an introduction to getting around in New City.  ","assistance"},

{"label","2"},
	{"fun",tourguideto3},
    {"ns","Okay, so you can start by telling me:  What does the sign say above the exterior of your team office?","VS_T1PXFUNCH_02.ogg"},
    {"pg","Professional Team Services","3"},
    {"pg","Deloitte and Touche, LLP","3"},
    {"pgs","Professional Services, LLP","2score","a"},
    {"pg","United Accounting Professionals Association","3"},
{"label","2score"},
    {"fun",addtouristscore},
    {"goto","3"},
{"label","3"},
    {"ns","Where are you told to go to do research in New City?","VS_T1PXFUNCH_03.ogg"},
    {"pg","Any computers in New City such as the ones in the Internet Café or team office","4"},
    {"pg","The newsstand by City Hall","4"},
    {"pg","The library","4"},
    {"pgs","All of these are places where research is available in New City","3score","b"},
{"label","3score"},
    {"fun",addtouristscore},
    {"goto","4"},
{"label","4"},
    {"ns","Very well, then. Now, here's a good question to see if you've been paying attention to details: What is the name of the team assistant in your team office who answers your general simulation questions?","VS_T1PXFUNCH_04.ogg"},
    {"pgs","Evelyn Hu","4score","c"},
    {"pg","Margaret Wong ","5"},
    {"pg","Jim Ojeda","5"},
    {"pg","None of these","5"},
{"label","4score"},
    {"fun",addtouristscore},
    {"goto","5"},   
{"label","5"},
    {"ns","Here's another question to see if you've been paying attention: what is the name of the CEO of your company?  ","VS_T1PXFUNCH_05.ogg"},
    {"pg","Mayor Judy Gonzalez","6"},
    {"pgs","Stan Freeman","5score","d"},
    {"pg","Evelyn Hu","6"},
    {"pg","Will Standon","6"},
{"label","5score"},
    {"fun",addtouristscore},
    {"goto","6"},   
{"label","6"},
    {"ns","So here is one last question to see how close you've been paying attention to what you're doing here: What is the name of the Mayor of New City?","VS_T1PXFUNCH_06.ogg"},
    {"pg","Mayor Will Standon","7"},
    {"pg","Mayor Luisa del Castillo","7"},
    {"pg","Mayor Evelyn Hu","7"},
    {"pgs","Mayor Judy Gonzalez","6score","e"},
{"label","6score"},
    {"fun",addtouristscore},
    {"goto","7"},

{"label","7"},
{"fun",incsq},
    {"fun",calctourcash},
    {"ns2","Well that's all the questions I have for you!  So, out of my 5 questions, you answered %d correctly. You earned $%d for your answers.  Remember, you can spend the money you get from answering challenge questions on anything that you may you want to buy in town!","VS_T1PXFUNCH_07.ogg","touristscore","tourcash"},
    {"pg","Okay, thanks! ","8"},

{"label","8"},
    {"ns","Well I hope you found my trivia challenge rewarding! If you really pay attention to details around Pay close attention, though – the questions are going to get a little tougher each time!","VS_T1PXFUNCH_08.ogg"},
    {"pg","Okay, great.  See you later!","end"},

{"label","atd1"},
    {"ns","As you work on your task, you can come back here and answer some trivia questions –and I will give you a bonus for each one you answer correctly.  Also, before you wrap up here in town, make sure you've explored and found all the people around town who may need your help. I hope that helps!","VS_T1PXFUNCH_10.ogg"},
    {"pg","Alright, I'll come back when I have gotten a little further in my assignment. I'll look around in the meantime.","end"},

{"label","atd2"},
    {"ns","I don't have another trivia challenge for you yet – but I hope you found the questions that I asked you earlier rewarding! Come back when you get your next assignment, and I will have more for you.  See you around!","VS_T1PXFUNCH_11.ogg"},
    {"pg","Ok, I'll check back with you another time.  Bye.","end"},
    --{"pg","Before I go, I am looking for help getting around.  Do you have a moment?","assistance"},
	

{"label","end"},
	{"fun3",storenlcscore,scoreconvo,scorestr},
}
 return dialogtext
