local dialogtext = {
	{"fun3",setvar,"scoreconvo","nlc_tg"},
{"if","tourguide","==",0,"asd"},
{"if","tourguide","==",1,"1"},
{"if","tourguide","==",2,"atd1"},
{"if","tourguide","==",3,"atd2"},

{"label","asd"},
    {"ns","Welcome to New City! I think I have seen you around town before –there are so many new faces these days! If I haven't mentioned this before, I am the local tour guide, and I know a bit about the area. I can help you if you need help getting around. ","VS_T2PXFUNCH_09.ogg"},
    {"pg","Thanks for the offer. I was just trying to pass through, though See you around!.","end"},
    {"pg","Thanks. I am looking for a way to make some personal money here in town.  Do you have any ideas?","atd1"},
    --{"pg","Great - I was actually looking for information.  Can you help?","assistance"},

{"label","1"},
    {"ns","Welcome back! I am happy to see you around town again. Remember, as the local tour guide, I know a bit about the area - and I can help you if you need help getting around. If you already know your way around town, though, I have a challenge for you: I'll give you a cash bonus if you can correctly answer some trivia questions.","VS_T2PXFUNCH_01.ogg"},
    {"pg","I am ready for one of your local trivia challenges! Let's begin.","2"},
    {"pg","I'm not sure I've paid enough attention to details around town this week – so I don't think I'm ready yet.","end"},
    --{"pg","Actually, I need help finding a location around town, could you help me?","assistance"},

{"label","2"},
	{"fun",tourguideto3},
    {"ns","Okay, so let's see if you've been paying attention – because like I may have told you, the questions get harder on each successive challenge.  Now, tell me:  Who approves your decision to hire vendors here in New City?","VS_T2PXFUNCH_02.ogg"},
    {"pg","I am responsible for approving vendors.","3"},
    {"pg","Professional Services' CEO Stan Freeman","3"},
    {"pgs","The mayor of New City.","2score","a"},
    {"pg","The Mayor's right hand man, Will Standon.","3"},
{"label","2score"},
    {"fun",addtouristscore},
    {"goto","3"},
{"label","3"},
    {"ns","Which of the following people give you contracts for your vendors?","VS_T2PXFUNCH_03.ogg"},
    {"pg","Evelyn Hu","4"},
    {"pg","The librarian","4"},
    {"pg","Mayor Judy Gonzalez","4"},
    {"pgs","Stan Freeman","3score","b"},
{"label","3score"},
    {"fun",addtouristscore},
    {"goto","4"},
{"label","4"},
    {"ns","Okay, so here's another question to see how closely you've been paying attention to details: Where does one redeem clothing for cash here in New City?","VS_T2PXFUNCH_04.ogg"},
    {"pgs","Pauline's","4score","c"},
    {"pg","Needles and Threads","5"},
    {"pg","Recycling containers and dumpsters around town","5"},
    {"pg","Pauline's or Recyclin containers and dumpsters around town","5"},
{"label","4score"},
    {"fun",addtouristscore},
    {"goto","5"},   
{"label","5"},
    {"ns","Here's another good one – let's see if you can tell me this: How many vendors are available for you to choose from for your task?","VS_T2PXFUNCH_05.ogg"},
    {"pg","It depends on the player role","6"},
    {"pgs","Four","5score","d"},
    {"pg","Six","6"},
    {"pg","Not sure","6"},
{"label","5score"},
    {"fun",addtouristscore},
    {"goto","6"},   
{"label","6"},
    {"ns","So here is one last question to test your attention to detail: What is the name of the security guard at City Hall?","VS_T2PXFUNCH_06.ogg"},
    {"pg","Sherriff Sam Shortback","7"},
    {"pg","Franco Manducci, PI","7"},
    {"pg","Elliot Gray","7"},
    {"pgs","Willie Ketchum","6score","e"},
{"label","6score"},
    {"fun",addtouristscore},
    {"goto","7"},

{"label","7"},
{"fun",incsq},
    {"fun",calctourcash},
    {"ns2","Well that's all the questions I have for you, for now. This time, out of my 5 questions, you answered %d correctly. You earned $%d for your answers.  Don't spend it all in one place!","VS_T2PXFUNCH_07.ogg","touristscore","tourcash"},
    {"pg","Thanks. ","8"},

{"label","8"},
    {"ns","Well I hope you found my challenge rewarding! Remember, paying attention to details around New City – and in life – is always good for your pocketbook.  I'll have another challenge later. Come back when you get your next task and I'll have even harder questions, with even bigger bonuses. ","VS_T2PXFUNCH_08.ogg"},
    {"pg","Okay, great.  See you later!","end"},

{"label","atd1"},
    {"ns","Each time you get about halfway done with your task, you can come back here and answer some trivia questions –and I will give you a bonus for each one you answer correctly.  Also, before you finish your task, make sure you've explored and found all the people who may need your help. They can reward you with cash bonuses as well. I hope that helps!","VS_T2PXFUNCH_10.ogg"},
    {"pg","Alright, I'll come back when I have gotten a little further in my assignment. I'll look around in the meantime.","end"},

{"label","atd2"},
    {"ns","I don't have any more trivia for you yet – but I hope you found the questions that I asked you earlier rewarding! Come back when you get your next assignment, and I may have more.  See you around!","VS_T2PXFUNCH_11.ogg"},
    {"pg","Ok, I'll check back with you another time.  Bye.","end"},
    --{"pg","Before I go, I am looking for help getting around.  Do you have a moment?","assistance"},
	

{"label","end"},
	{"fun3",storenlcscore,scoreconvo,scorestr},
}
 return dialogtext
