local dialogtext = {
{"if","player","~=",3,"random"},
{"if","week","<",4,"random"},
{"if","w3vendor","==",4,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","The file is parsed! I'm ready to work!","vs_w3p3vd_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","Data configuration complete, HiTek will do a great job for you.","vs_w3p3vd_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","The file has not been parsed, we will not be working together.","vs_w3p3vd_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","HiTek Protection will not have the honor of processing your security data.","vs_w3p3vd_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","It all comes down to the data.","vs_w3p3vd_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","Control, alt but never delete.","vs_w3p3vd_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
