local dialogtext = {
{"if","player","~=",2,"random"},
{"if","week","<",3,"random"},
{"if","w2vendor","==",2,"1"},
{"goto","3"},

{"label","random"},
{"if","rnddialog","==",0,"5"},
{"if","rnddialog","==",2,"5"},
{"goto","6"},
{"label","1"},
{"if","rnddialog","==",0,"2"},
{"if","rnddialog","==",2,"2"},
    {"ns","Mondo good choice, going with us.","vs_w2p2vb_rdm1.wav"},
	{"wait","end"},
{"label","2"},
    {"ns","We'll do a mondo good job for you, don't worry!","vs_w2p2vb_rdm2.wav"},
	{"wait","end"},
{"label","3"},
{"if","rnddialog","==",0,"4"},
{"if","rnddialog","==",2,"4"},
    {"ns","Mondo mistake picking the other vendor.","vs_w2p2vb_rdm3.wav"},
	{"wait","end"},
{"label","4"},
    {"ns","You're going to need mondo good luck without us on the team.","vs_w2p2vb_rdm4.wav"},
	{"wait","end"},
{"label","5"},
    {"ns","Mondo is as mondo does.","vs_w2p2vb_rdm5.wav"},
	{"wait","end"},
{"label","6"},
    {"ns","I need a mondo new condo.","vs_w2p2vb_rdm6.wav"},
	{"wait","end"},    
{"label","end"},
}
 return dialogtext
